name: hiersplit
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - libmetis=5.1
  - pip
  - pip:
      - -r requirements.txt
      - -e .[test]
